"""init

Revision ID: ce74f5fccb46
Revises: 
Create Date: 2025-06-11 01:02:13.963376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce74f5fccb46'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('balacne_left', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('accounts_pkey')),
    sa.UniqueConstraint('username', name=op.f('accounts_username_key'))
    )
    op.create_table('tasks',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('app_bundle', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('tasks_pkey'))
    )
    op.create_index(op.f('tasks_id_idx'), 'tasks', ['id'], unique=False)
    op.create_table('account_tokens',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('cookies', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('account_tokens_account_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('account_tokens_pkey'))
    )
    op.create_index(op.f('account_tokens_id_idx'), 'account_tokens', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('account_tokens_id_idx'), table_name='account_tokens')
    op.drop_table('account_tokens')
    op.drop_index(op.f('tasks_id_idx'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_table('accounts')
    # ### end Alembic commands ###
